kd:
  use_pregen: true
  pregen_dir: data/kd_corpus/qwen8b_S64_topk64
  total_steps: 10000
  batch_size: 4
  log_every: 20

  # optimizer
  lr: 1.0e-4
  weight_decay: 0.0
  warmup_ratio: 0.05
  betas: [0.9, 0.95]

  # KD divergence
  distill_temp: 1.0
  topk_tail: "bucket"   # "bucket" | "ignore"
  # weighting
  margin_gamma: 0.5
  margin_center: 1.0
  w_min: 0.2
  mismatch_lambda: 0.3
