draft:
  name: Qwen/Qwen3-0.6B

lora:
  target_modules: ["q_proj","k_proj","v_proj","o_proj","up_proj","down_proj","gate_proj"]
  r: 64
  alpha: 32
  dropout: 0.05
  task_type: "CAUSAL_LM"
  qlora: false    # set true if you want 4bit

training:
  device: cuda
  dtype: bf16
  seed: 1234
  max_grad_norm: 1.0
